<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Laporan Penjualan - {{ $periode }}</title>
    <style>
        @page {
            margin: 1.5cm;
        }

        body {
            font-family: 'Helvetica', Arial, sans-serif;
            font-size: 11px;
            color: #333;
            line-height: 1.5;
        }

        /* HEADER SECTION */
        .header {
            text-align: center;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
            font-size: 18px;
            color: #2c3e50;
            text-transform: uppercase;
        }

        .header p {
            margin: 5px 0 0;
            font-size: 10px;
            color: #7f8c8d;
        }

        /* INFO SECTION */
        .info-container {
            width: 100%;
            margin-bottom: 20px;
        }

        .info-table {
            width: 100%;
            border-collapse: collapse;
        }

        .info-table td {
            padding: 2px 0;
            vertical-align: top;
        }

        .label {
            width: 100px;
            color: #7f8c8d;
            font-weight: bold;
        }

        /* DATA TABLE */
        table.data {
            width: 100%;
            border-collapse: collapse;
        }

        table.data th {
            background-color: #2c3e50;
            color: #ffffff;
            text-align: center;
            padding: 10px 5px;
            font-size: 10px;
            text-transform: uppercase;
            border: 1px solid #2c3e50;
        }

        table.data td {
            padding: 8px 5px;
            border-bottom: 1px solid #bdc3c7;
            border-left: 1px solid #eee;
            border-right: 1px solid #eee;
        }

        .row-even {
            background-color: #f9f9f9;
        }

        /* STATUS BADGE */
        .badge {
            padding: 3px 8px;
            border-radius: 10px;
            font-size: 9px;
            font-weight: bold;
            text-align: center;
        }

        .status-selesai {
            background-color: #d4edda;
            color: #155724;
        }

        .status-batal {
            background-color: #f8d7da;
            color: #721c24;
        }

        .status-default {
            background-color: #e2e3e5;
            color: #383d41;
        }

        /* SUMMARY SECTION */
        .summary-wrapper {
            margin-top: 20px;
            float: right;
            width: 300px;
        }

        .summary-table {
            width: 100%;
            border-collapse: collapse;
        }

        .summary-table td {
            padding: 8px;
            border-bottom: 1px solid #eee;
        }

        .total-label {
            font-size: 12px;
            font-weight: bold;
            color: #2c3e50;
        }

        .total-amount {
            font-size: 14px;
            font-weight: bold;
            color: #2c3e50;
            text-align: right;
        }

        /* FOOTER */
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            font-size: 9px;
            color: #bdc3c7;
            border-top: 1px solid #eee;
            padding-top: 5px;
            text-align: center;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }
    </style>
</head>

<body>

    <div class="header">
        <h2>LAPORAN PENJUALAN</h2>
        <p>Generated by Digital Sales System</p>
    </div>

    <div class="info-container">
        <table class="info-table">
            <tr>
                <td class="label">Periode</td>
                <td>: {{ $periode }}</td>
                <td class="label" align="right">Tanggal Cetak</td>
                <td align="right">: {{ now()->format('d F Y H:i') }}</td>
            </tr>
            <tr>
                <td class="label">Total Transaksi</td>
                <td>: {{ $laporan->count() }} Record(s)</td>
                <td class="label" align="right">Petugas</td>
                <td align="right">: {{ Auth::user()->name ?? 'System' }}</td>
            </tr>
        </table>
    </div>

    @php $totalPenjualan = 0; @endphp

    <table class="data">
        <thead>
            <tr>
                <th width="30">No</th>
                <th width="120">Kode Invoice</th>
                <th>Tanggal Transaksi</th>
                <th width="100">Status</th>
                <th width="150" class="text-right">Total Nominal</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($laporan as $index => $p)
                @php $totalPenjualan += $p->total; @endphp
                <tr class="{{ $index % 2 == 1 ? 'row-even' : '' }}">
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td style="font-weight: bold; color: #34495e;">{{ $p->kode_invoice }}</td>
                    <td class="text-center">{{ $p->created_at->format('d/m/Y H:i') }}</td>
                    <td class="text-center">
                        @php
                            $statusClass = 'status-default';
                            if ($p->status == 'selesai') {
                                $statusClass = 'status-selesai';
                            }
                            if ($p->status == 'batal') {
                                $statusClass = 'status-batal';
                            }
                        @endphp
                        <span class="badge {{ $statusClass }}">
                            {{ strtoupper($p->status) }}
                        </span>
                    </td>
                    <td class="text-right" style="font-weight: bold;">
                        Rp {{ number_format($p->total, 0, ',', '.') }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center" style="padding: 20px; color: #95a5a6;">
                        Tidak ada data ditemukan untuk periode ini.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary-wrapper">
        <table class="summary-table">
            <tr>
                <td class="total-label">Grand Total</td>
                <td class="total-amount">
                    Rp {{ number_format($totalPenjualan, 0, ',', '.') }}
                </td>
            </tr>
        </table>
        <p style="font-size: 8px; font-style: italic; color: #95a5a6; margin-top: 5px; text-align: right;">
            * Seluruh nilai dalam mata uang Rupiah (IDR)
        </p>
    </div>

    <div class="footer">
        Laporan ini sah dan dihasilkan secara otomatis oleh sistem pada {{ now()->format('d/m/Y H:i:s') }}.
        Halaman 1 dari 1
    </div>

</body>

</html>
